import sys


def raise_error(err, code=1):
    sys.exit(err)

